# Generated by Django 5.1.2 on 2024-10-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('lineNo', models.IntegerField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('UnitNo', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=2)),
                ('total', models.DecimalField(decimal_places=2, max_digits=2)),
                ('expiryDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unitNo', models.IntegerField(primary_key=True, serialize=False)),
                ('unitName', models.CharField(max_length=100)),
            ],
        ),
    ]
