# Generated by Django 5.1.2 on 2024-10-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
